#!/bin/bash

# Deploy Frontend with Correct API Endpoint
# This script builds and deploys the frontend with the correct API endpoint

set -euo pipefail

echo "🚀 Deploying Frontend to S3/CloudFront"
echo ""

# Get API endpoint from CloudFormation
echo "📡 Fetching API endpoint from AWS..."
API_ENDPOINT=$(aws cloudformation describe-stacks \
  --stack-name WorkstationApi \
  --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' \
  --output text \
  --region us-west-2)

if [ -z "$API_ENDPOINT" ]; then
  echo "❌ Error: Could not retrieve API endpoint from CloudFormation"
  echo "   Make sure the WorkstationApi stack is deployed"
  exit 1
fi

echo "✅ API Endpoint: $API_ENDPOINT"
echo ""

# Get Admin API endpoint from CloudFormation
echo "📡 Fetching Admin API endpoint from AWS..."
ADMIN_API_ENDPOINT=$(aws cloudformation describe-stacks \
  --stack-name WorkstationAdminApi \
  --query 'Stacks[0].Outputs[?OutputKey==`AdminApiUrl`].OutputValue' \
  --output text \
  --region us-west-2 2>/dev/null || echo "")

if [ -z "$ADMIN_API_ENDPOINT" ]; then
  echo "⚠️  Warning: Could not retrieve Admin API endpoint from CloudFormation"
  echo "   Using main API endpoint as fallback"
  ADMIN_API_ENDPOINT="$API_ENDPOINT"
fi

echo "✅ Admin API Endpoint: $ADMIN_API_ENDPOINT"
echo ""

# Get other config from CloudFormation
echo "📡 Fetching Cognito configuration..."
USER_POOL_ID=$(aws cloudformation describe-stacks \
  --stack-name WorkstationInfrastructure \
  --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' \
  --output text \
  --region us-west-2 2>/dev/null || echo "")

USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
  --stack-name WorkstationInfrastructure \
  --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
  --output text \
  --region us-west-2 2>/dev/null || echo "")

# Create or update .env.local
echo "📝 Creating frontend/.env.local..."
cat > frontend/.env.local << EOF
# Auto-generated by deploy-frontend.sh
NEXT_PUBLIC_AWS_REGION=us-west-2
NEXT_PUBLIC_API_ENDPOINT=$API_ENDPOINT
NEXT_PUBLIC_ADMIN_API_ENDPOINT=$ADMIN_API_ENDPOINT
NEXT_PUBLIC_USER_POOL_ID=$USER_POOL_ID
NEXT_PUBLIC_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
NEXT_PUBLIC_LOCAL_ADMIN_MODE=false
EOF

echo "✅ Environment configured"
echo ""

# Build frontend
echo "🔨 Building frontend..."
cd frontend
npm run build
cd ..

echo "✅ Frontend built successfully"
echo ""

# Upload to S3
echo "📤 Uploading to S3..."
S3_BUCKET="${FRONTEND_S3_BUCKET:-$(aws cloudformation describe-stacks --stack-name WorkstationWebsite --query 'Stacks[0].Outputs[?OutputKey==`WebsiteBucketName`].OutputValue' --output text 2>/dev/null)}"

if [ -z "$S3_BUCKET" ]; then
  echo "Error: Could not determine S3 bucket."
  echo "Set FRONTEND_S3_BUCKET environment variable,"
  echo "or ensure the WorkstationWebsite stack is deployed."
  exit 1
fi

aws s3 sync frontend/out/ s3://$S3_BUCKET/ --delete --region us-west-2

echo "✅ Uploaded to S3"
echo ""

# Invalidate CloudFront cache
echo "🔄 Invalidating CloudFront cache..."
DISTRIBUTION_ID="${CLOUDFRONT_DISTRIBUTION_ID:-$(aws cloudformation describe-stacks --stack-name WorkstationWebsite --query 'Stacks[0].Outputs[?OutputKey==`DistributionId`].OutputValue' --output text 2>/dev/null)}"

if [ -z "$DISTRIBUTION_ID" ]; then
  echo "Error: Could not determine CloudFront distribution ID."
  echo "Set CLOUDFRONT_DISTRIBUTION_ID environment variable,"
  echo "or ensure the WorkstationWebsite stack is deployed."
  exit 1
fi
INVALIDATION_ID=$(aws cloudfront create-invalidation \
  --distribution-id $DISTRIBUTION_ID \
  --paths "/*" \
  --query 'Invalidation.Id' \
  --output text \
  --region us-west-2)

echo "✅ CloudFront invalidation created: $INVALIDATION_ID"
echo ""

# Wait for invalidation to complete
echo "⏳ Waiting for CloudFront invalidation to complete..."
aws cloudfront wait invalidation-completed \
  --distribution-id $DISTRIBUTION_ID \
  --id $INVALIDATION_ID \
  --region us-west-2

echo ""
echo "🎉 Deployment complete!"
echo ""
echo "📋 Configuration Summary:"
echo "   API Endpoint: $API_ENDPOINT"
echo "   Admin API Endpoint: $ADMIN_API_ENDPOINT"
echo "   CloudFront Distribution: $DISTRIBUTION_ID"
echo "   S3 Bucket: $S3_BUCKET"
echo ""
echo "✅ You can now test the application with the correct API endpoint configured!"